#!/usr/bin/env bash

set -e

BUILD_DIR='build'
GITHUB_REPO='reactstrap/reactstrap.github.io'

success() {
  echo -e "\033[32;1m$1"
}

error() {
  echo -e "\033[31;1m$1"
}

if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
  echo "Deploying documentation"
else
  success "Not building master branch. Skipping deploy."
  exit 0
fi

if [ -z "$GITHUB_TOKEN" ]; then
  error "Environment variable GITHUB_TOKEN does not exist. Stopping deploy."
  exit 1
fi

git checkout -B gh-pages

npm run build

if [ ! -d $BUILD_DIR ]; then
  error "Build directory does not exist. Stopping deploy."
  exit 1
fi

echo "Committing docs to gh-pages"
git add -f $BUILD_DIR
git commit -am "Updating docs from commit: $TRAVIS_COMMIT"
git filter-branch -f --prune-empty --subdirectory-filter build

echo "Setting up ghtoken for publishing"
git remote rm origin
git remote add origin https://${GITHUB_TOKEN}@github.com/${GITHUB_REPO}.git
git config user.name "Travis-CI"
git config user.email "reactstrap@github.io"

echo "Pushing gh-pages to origin"
git push origin gh-pages > /dev/null 2>&1
git checkout -

success "Successfully published documentation for commit: $TRAVIS_COMMIT!"
